import os

MAX_X = 900
MAX_Y = 600
FRAME_LENGTH = 0.08
FRAME_RATE = 30
STARTING_WORDS = 5
PATH = os.path.dirname(os.path.abspath(__file__))
LIBRARY = open(PATH + "/words.txt").read().splitlines()

DEFAULT_WORD_HEIGHT = 20
DEFAULT_WORD_SPEED = -1

DEFAULT_FONT_SIZE = 16

DEFAULT_TEXT_OFFSET = 5

STARTING_SPAWN_RATE = 30
SPAWNRATE_FACTOR = 1000
